### ISSUE TITLE
Make Profile Page for posters

### ISSUE THREAD

**Issue by allyharrison** [codersforcauses/penni#126]
## Basic Information
Create a profile page for the posters (frame 1582) which is very similar to the one already made for the bidders.
![image](https://github.com/user-attachments/assets/e2d0a60a-57da-4980-9b58-9d3d24eda2e6)

## Other Information
Can be made reusing profile page tag components from the bidders' profile page: #75 #81

**Comment by ErikaKK** [comment]
This one will be done in #157
