### ISSUE TITLE
Create Onboarding Screens ( carousel-like ) Component

### ISSUE THREAD

**Issue by yunho7687** [codersforcauses/penni#13]
## Basic Information
Create an onboarding screens component. These screens should be displayed when the user first opens the app, providing a carousel-like introduction to the app's key features and benefits.

## Requirements:
- Create a React component for the onboarding screens.
- Implement a carousel to navigate through the different onboarding slides.
-Navigation ("Prev/Next", progress step) 
- Include a skip button to allow users to bypass the onboarding process.
- Ensure smooth transitions between onboarding slides.
- Ensure a smooth transition from the onboarding screens to the main app interface.
- from each picture ensure colour change of time and battery according to image background
-note that after each next, there are consecutive dots at front bottom placement of the image that change shape when specifying which image the user is currently at

[Figma design](https://www.figma.com/design/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=5996-22124&t=w0t63mb6QaHbIOjN-0)

![image](https://github.com/codersforcauses/penni/assets/75521446/e6622c7f-92cf-4273-ae56-7d73a98ca4ef)

**Comment by keyman015** [comment]
The bulk of it has been completed as seen in a sample picture:
![image](https://github.com/codersforcauses/penni/assets/25141441/ca7e6ddc-f2af-4fe2-8834-4362544956c8)
(ignore the tanstack icon - I can't seem to get rid of it)

However, I am unsure as to the nature of "smooth transitions". Does this mean like a sliding animation or something?

**Comment by Julie-Salazar** [comment]
> The bulk of it has been completed as seen in a sample picture: ![image](https://private-user-images.githubusercontent.com/25141441/344134564-ca7e6ddc-f2af-4fe2-8834-4362544956c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDI0MzQsIm5iZiI6MTcxOTY0MjEzNCwicGF0aCI6Ii8yNTE0MTQ0MS8zNDQxMzQ1NjQtY2E3ZTZkZGMtZjJhZi00ZmUyLTg4MzQtNDM2MjU0NDk1NmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA2MjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYmIxYmQ2M2QwMDViMDQ4NTkxY2IwNzhlZDEzZmIyNDkyZGZmNDljZWI4OTdmNGYzNDZjNDM2NWQxOTA5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F2tsq31B1OXqKwV-V3lyC82-yX4c8wbZVZvYV7b9PJU) (ignore the tanstack icon - I can't seem to get rid of it)
> 
> However, I am unsure as to the nature of "smooth transitions". Does this mean like a sliding animation or something?

hello! please see issue https://github.com/codersforcauses/penni/issues/30 yes sliding images to left uppon clicking "Next"

**Comment by keyman015** [comment]
~~@Julie-Salazar~~ are we allowed to use external packages to provide the basic carousel base then build the component around it? As we already use button from shadcn ui, would it then be possible to use https://ui.shadcn.com/docs/components/carousel?
As this has a transition built into it from what I can see.

Edit: Yunho has permitted it.
