### ISSUE TITLE
Sign-up page enhancement

### ISSUE THREAD

**Issue by SeiKasahara** [codersforcauses/penni#134]
## Basic Information

- [ ]  Username and email address should be checked if it's unique when users click the next button, since the database has unique constraint.

Considering async function example be like
```tsx
export const checkUnique = async (
  input: string,
  type: 'email' | 'username',
): Promise<string> => {
  try {
    const response = await api.get(`/check-unique?${type}=${input}`);
    // axios automatically parses the response as JSON if the content type is application/json
    const data = response.data;

    if (data[`${type}_taken`]) {
      return data[`${type}_error_message`];
    }
    return '';
  } catch (error) {
    //... error handling block
  }
};
```
The backend should return a error_message to frontend.

- [ ] The password page should be added, including following functions:

1. Password should be checked as same as confirm password. Example function is like:
```tsx
function passwordValidation(password: string, repeatPassword: string) {
  if (repeatPassword != password) {
    return false;
  }
  return true;
}
```
2. [Optional Enhancement] Considering security issues, the strength of the user's entered password should be checked.

**Comment by SeiKasahara** [comment]
Preparing to combine #65 works on this branch. And also make reconstrcuction on it.

**Comment by ErikaKK** [comment]
This was done in #65
