### ISSUE TITLE
Sign-in page

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#135]
## Basic Information
I can only find sign-up under `/page` so the sign-in page is probably missing.

But what does it mean to "sign in"? If there is a "sign-in" and a "sign-out", does that mean the existence of "sign-up" implies a "sign-down"? What if we wish to sign sideways? What if we wish not to sign, but to write? These are truly philosophically profound inquiries that one must ponder and reflect upon :thinking:

**Comment by SeiKasahara** [comment]
Signout can be added in users' main page?
