### ISSUE TITLE
[Bugfix]: fixed import components path not found error.

### ISSUE THREAD

**Issue by ArcueidShiki** [codersforcauses/penni#144]
## Basic Information
**@/components/ui/top-navtab not found**

## Other Information
**Correct import path to @/components/ui/bidder/top-navtab**
https://github.com/codersforcauses/penni/issues/144#issue-2418792605

**Comment by ErikaKK** [comment]
Sorry I didn't see this component is also used in poster page. Would you mind moving this component out of /bidder folder and update imports for me? Thanks!
