### ISSUE TITLE
Onboarding page Refactoring

### ISSUE THREAD

**Issue by yunho7687** [codersforcauses/penni#16]
## Basic Information
Create the Onboarding page and components needed
[Figma design](https://www.figma.com/design/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=5996-22124&t=w0t63mb6QaHbIOjN-0)

## Other Information
create it in the "/pages"

## UPDATE:
- Refactor Onboarding component into a page under `/page`

**Comment by SodaVolcano** [comment]
- [ ] `OnboardingPage` component
- [ ] Onboarding background
    - Displays any arbitrary image URL
    - White fade at the bottom
- [ ] Bottom text component with specified styling
    - Displays arbitrary text, fixed to be two-line high (i.e. character limit)
- [ ] Navigation ("Prev/Next", pagination dots)
    - Pressing "Next" or "Prev" updates the background image and text

Potentially separate into smaller issues?

**Comment by SodaVolcano** [comment]
idk the purpose of this so I'm closing this issue, onboarding page seems fine
