### ISSUE TITLE
Bottom Navigator Component 

### ISSUE THREAD

**Issue by Julie-Salazar** [codersforcauses/penni#27]
Botton navigator according to figma outlining the:
- my tasks
- market
- me

please refer to the "Bottom Navigation" component in the figma pages:

<img width="413" alt="Screenshot 2024-06-29 at 14 12 13" src="https://github.com/codersforcauses/penni/assets/92288226/894a442e-aa7c-4fde-be02-c7b143370db4">

**Comment by ErikaKK** [comment]
<img width="380" alt="Screenshot 2024-06-30 at 3 59 16 PM" src="https://github.com/codersforcauses/penni/assets/98962967/52eed4d8-63ae-4fcf-abc5-e9ca85c91a8c">
Hi, this is what I made so far. Should I add onClick color change to this one? @Julie-Salazar
