### ISSUE TITLE
Sliding transition on carousel component images

### ISSUE THREAD

**Issue by Julie-Salazar** [codersforcauses/penni#30]
Every time the Next button is pressed there should be a sliding to left transition for each image, maybe about a 1-2 sec transition each time >> suit to taste 

linked issues https://github.com/codersforcauses/penni/issues/13

**Comment by mouper** [comment]
This issue is now resolved in the original [onboarding carousel issue 13](https://github.com/codersforcauses/penni/issues/13), do we need to move/add any changes to this issue as well?

**Comment by keyman015** [comment]
Closed as of PR https://github.com/codersforcauses/penni/pull/83 and the related issue https://github.com/codersforcauses/penni/issues/13
