### ISSUE TITLE
Task details

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#35]
Headings and texts with descriptions about a task.

![image](https://github.com/codersforcauses/penni/assets/100743188/fae2765e-3f00-4e16-ab0d-8b8f9039ccce)

## General Information
- **Location:** `/components`
- **Purpose:** Display details about a task. Used by Frame 1575, 1572, 1552...
- **Behaviour:** Take in heading-text pairs?

**Comment by Julie-Salazar** [comment]
Hey! just wondering if you could put more detail when making issues because this will also be maintained in the future by others, some structure for it could be:
location:
purpose:
behavior:

**Comment by SodaVolcano** [comment]
> Hey! just wondering if you could put more detail when making issues because this will also be maintained in the future by others, some structure for it could be: location: purpose: behavior:

Okay sure, I'll go ahead and change the issues I've made so far.

**Comment by mouper** [comment]
<img width="349" alt="Screenshot 2024-06-29 at 7 05 07 pm" src="https://github.com/codersforcauses/penni/assets/51354655/30899d1d-7bb6-436d-abb9-ceb708dc129b">

The bulk of this issue has been completed (as seen in the above screenshot), however, I am unsure if it fits the 'behaviour' requirements.

**Comment by keyman015** [comment]
I have added the heading-text pair as a prop to the component, which takes in data using the `data` prop which should look like json using only text (or null for null column in database). If a field in the data prop is empty or null it displays `N/A` by default, this behavior can be modified using the prop `emptyContentPlaceholder`.

**Comment by mouper** [comment]
Fixed a simple bug so the subheading titles are displayed instead of the db column names, apart from that it looks good to me, @Julie-Salazar are there any more changes we need to make?
