### ISSUE TITLE
Implement the database model according to ERD from Figma

### ISSUE THREAD

**Issue by 0XFF-96** [codersforcauses/penni#38]
## Basic Information
ERD Diagram Link - https://cottony-rover-487.notion.site/ERD-4838acae80e34c2ab001e3446956d178

Figma Link - https://www.figma.com/proto/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=5996-22146&t=s4b05Gg69rb6KRmZ-0&scaling=scale-down&content-scaling=fixed&page-id=5996%3A22124&starting-point-node-id=5996%3A23356

**Comment by keyman015** [comment]
For the database, can the tasks table be modified from the ERD to add a column for `category` as this is missing and is assumed in the figma design (https://github.com/codersforcauses/penni/issues/35). Additionally, is `deadline` the expiry date of the task or the time duration of the task itself? Thanks.

**Comment by 0XFF-96** [comment]
> For the database, can the tasks table be modified from the ERD to add a column for `category` as this is missing and is assumed in the figma design (#35). Additionally, is `deadline` the expiry date of the task or the time duration of the task itself? Thanks.

Yes, I have added a category Column, and updated it on ERD
