### ISSUE TITLE
Global CSS style for font

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#42]
## Basic Information
Create global CSS style classes for the fonts, see [Figma](https://www.figma.com/design/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=449-90&t=Tx5T1Anqr6fBjZy9-0)

![image](https://github.com/codersforcauses/penni/assets/100743188/9f156963-d00c-47b5-9dd3-e2a10f482165)

e.g. 
```css
.penni-h1 {
    @apply text-3x1 ...
}
```

## Other Information
- **Location**: `/styles/styles.css` (include in `/pages/_app.tsx`)
- **Behaviour**: Make style fonts globally accessible
- **Purpose**: Make the codebase more concise. Instead of defining the same style in different components, we can reuse the same CSS class.

**Comment by SeiKasahara** [comment]
I am considering if I need to download this font
