### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#50]
## Basic Information
A "popup" on the bottom of the screen where any arbitrary component can be inserted into it.

- **Location**: `/components/card.tsx`
- **Behaviour**: Slides up from the bottom of the screen on top of the screen, and can be closed by clicking the "X" button.

![image](https://github.com/codersforcauses/penni/assets/100743188/98ccb4af-ef32-4337-a183-03fc86cbd0f6)

- [ ] Page styling with border rounding (see tailwind config file for penni radius class)
- [ ] Closes the page when "X" is pressed
- [ ] Sliding animation when it opens/closes

## Usage
```html
<Card>
  <Callout .../>
  // whatever
</Card>

<Card>
   <Form>
   <Title content="Your password">
      <SIngleLIneInput .../>
      <Button>
    </Form>
</Card>
```

**Comment by keyman015** [comment]
Closed as of https://github.com/codersforcauses/penni/pull/117.
