### ISSUE TITLE
Design database schema (ERD)

### ISSUE THREAD

**Issue by yunho7687** [codersforcauses/penni#6]
It's always a good idea to have a high-level overview of the application before starting. One way is by thinking about how data is stored and the relationships between them.

Complete and refine the ER diagram below according to the Figma design. Have a think through and once ready, run it by one of the helpers/committee to confirm
[Figma ERD link](https://www.figma.com/board/shdGTBgmK90jEMBjPlQcjK/ERD-of-Penni?node-id=0-1&t=5WNHcNeCfQdDgoxA-0)

**Comment by 0XFF-96** [comment]
Hi, I can take over this task. May I ask what the deadline for this task is?

**Comment by Julie-Salazar** [comment]
> Hi, I can take over this task. May I ask what the deadline for this task is?

preferably have most of it done by this coming Saturday session! and then we can look at it all together, this will also inform decision of how to delegate diff issues etc

**Comment by 0XFF-96** [comment]
https://cottony-rover-487.notion.site/ERD-4838acae80e34c2ab001e3446956d178

**Comment by 0XFF-96** [comment]
> https://cottony-rover-487.notion.site/ERD-4838acae80e34c2ab001e3446956d178

This task have been finished. But I will leave the issue opened for ongoing disccusion
