### ISSUE TITLE
Replace all font styling with global font classes

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#65]
## Basic Information
Replace all font styling with the styling classes defined in #42 once it's merged for consistency (very fun chore)

**Comment by SeiKasahara** [comment]
Should this be a last check that ensuring every pages use the global font classes?

**Comment by SodaVolcano** [comment]
Not sure what you mean by last check? 

All PRs from this point should use the global font classes, any that don't use the style should be corrected during code review so, changes made for this issue can be merged in a PR.
