### ISSUE TITLE
Create proper issues according to the Figma design

### ISSUE THREAD

**Issue by yunho7687** [codersforcauses/penni#7]
### Feel free to create proper issues
Please check the Figma design and create issues
 [Figma](https://www.figma.com/design/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=5996-22124&t=7QxxhVGt8qdrF9t7-0)

**Comment by SodaVolcano** [comment]
I'm going to close this. New issues have been and will be created over time so this issue is pretty much addressed.
