### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#75]
## Basic Information
Make a profile page displaying a user's... well, profile. Place in `/components/profile.tsx`. Maybe break this down into smaller components and make an issue for each of them?

![image](https://github.com/codersforcauses/penni/assets/100743188/0e189911-5f3d-48bd-8505-3c68a8e24c2d)
- [x] #123

**Comment by keyman015** [comment]
Closed as of https://github.com/codersforcauses/penni/pull/117.

**Comment by keyman015** [comment]
Sorry. Thats my bad
