### ISSUE TITLE
Dark mode theming

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#82]
## Basic Information
I love dark mode

pls add ability to swap to dark mode in the code, and worry about component that switch the theme in a separate issue

**Comment by SodaVolcano** [comment]
Found a way that doesn't require adding `dark:` onto every class. See https://stackoverflow.com/questions/72117668/tailwind-colors-based-on-dark-mode

Essentially we use different colour definitions if the class `dark` is present in the parent element. Would be better to replace all `penni` colours in `tailwind.config.ts` to use these variables and remove the `-light-mode` and `-dark-mode` suffixes in some of the colours so we just have one colour (will need to find where those classes are used throughout the project though).

**Comment by allyharrison** [comment]
Thanks for this @SodaVolcano, I followed your suggestion along with this guide from ShadCN: https://ui.shadcn.com/docs/dark-mode/next 

Right now the mode defaults to system preference. 

Next/final step is to add a toggle (example on that ShadCN page). Can probably incorporate the dropdown from issue #72 once it gets merged onto main. I'll make a new issue for it 🌚
