### ISSUE TITLE
Report A Problem Page

### ISSUE THREAD

**Issue by mouper** [codersforcauses/penni#90]
## Basic Information
<img width="280" alt="Screenshot 2024-07-06 at 3 56 45 pm" src="https://github.com/codersforcauses/penni/assets/51354655/daeceec7-f400-4430-9d00-fd0566229b6d">

- [ ] Subject Title Text 
- [ ] Description Text
- [ ] Description Image Upload
- [ ] Submit Report Button

## Other Information

**Comment by keyman015** [comment]
> Branch [issue-90-Report_A_Problem_View](https://github.com/codersforcauses/penni/tree/issue-90-Report_A_Problem_View) created!

Deleted unused branch.

**Comment by keyman015** [comment]
Closed as PR https://github.com/codersforcauses/penni/pull/118 has been merged into main.
